https://www.machinelearningplus.com/python/101-numpy-exercises-python/

1. Import numpy as np and see the version

In [6]:
import numpy as np
print (np.__version__)

1.16.2


2. How to create a 1D array?
Q. Create a 1D array of numbers from 0 to 9


In [9]:
no = np.arange(0,10)
print (no)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
arr = np.array(no)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?
Q. Create a 3×3 numpy array of all True’s

In [17]:
np.ones((3,3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])