https://www.machinelearningplus.com/python/101-numpy-exercises-python/

1. Import numpy as np and see the version

In [1]:
import numpy as np
print (np.__version__)

1.15.4


2. How to create a 1D array?
Q. Create a 1D array of numbers from 0 to 9


In [2]:
no = np.arange(0,10)
print (no)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
arr = np.array(no)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?
Q. Create a 3×3 numpy array of all True’s

In [4]:
np.ones((3,3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. How to extract items that satisfy a given condition from 1D array? <br>
Extract all odd numbers from arr

In [5]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# My solution
odd =[]
for i in arr:
    if i%2 > 0:
        odd = np.append(odd,[i])
        
odd

array([1., 3., 5., 7., 9.])

In [7]:
arr[arr%2 ==1] # Solution from web

array([1, 3, 5, 7, 9])

5. How to replace items that satisfy a condition with another value in numpy array? <br>
Replace all odd numbers in arr with -1


In [8]:
#My solution
for i in arr:
    if i%2 > 0:
        arr[i] = -1
        
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
# Solution from Web
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6. How to replace items that satisfy a condition without affecting the original array?
Replace all odd numbers in arr with -1 without changing arr

In [16]:
# My solution
odd_1 = []
for i in arr:
    if i%2 > 0:
        odd_1 = np.append(odd_1, -1)
    else:
        odd_1 = np.append(odd_1,i)
print (arr)
print (odd_1)

[0 1 2 3 4 5 6 7 8 9]
[ 0. -1.  2. -1.  4. -1.  6. -1.  8. -1.]


In [21]:
arr = np.arange(10)
odd_1 = np.where (arr % 2 == 1, -1, arr)
print (arr)
print (odd_1)
odd_1.shape

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


(10,)